[package]
name = "rtt-target"
description = "Target side implementation of the RTT (Real-Time Transfer) I/O protocol"
version = "0.2.2"
edition = "2018"
readme = "../README.md"
keywords = ["no-std", "embedded", "debugging", "rtt"]
license = "MIT"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]
repository = "https://github.com/mvirkkunen/rtt-target"

[dependencies]
ufmt-write = "0.1.0"

# Platform specific stuff
cortex-m = { version = "0.6.2", optional = true }

# Dependencies used only for examples
ufmt = { version = "0.1.0", optional = true }
cortex-m-rt = { version = "0.6.12", optional = true }
panic-halt = { version = "0.2.0", optional = true }

[features]
examples-cortex-m = ["cortex-m", "cortex-m-rt", "panic-halt", "ufmt"]

[[example]]
name = "cortex-m-custom"
required-features = ["examples-cortex-m"]

[[example]]
name = "cortex-m-print"
required-features = ["examples-cortex-m"]

[[example]]
name = "cortex-m-ufmt"
required-features = ["examples-cortex-m"]

# This is for the examples
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"

[package.metadata.docs.rs]
features = ["cortex-m"]