[package]
name = "panic-test"
version = "0.1.0"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m-rt = "0.6.12"
panic-rtt-target = { path = "../panic-rtt-target", features = ["cortex-m"] }
rtt-target = { path = "../rtt-target" }
